const u = (id) =>
  `https://images.unsplash.com/${id}?w=600&q=80&auto=format&fit=crop`

export const DEMO_SETTINGS = {
  storeName: 'MJ FASHION WORLD',
  tagline: 'Fashion for everyone',
  announcement: '🎉 Flat 20% OFF on orders above ₹999 — use no coupon needed!',
  upiId: 'yourname@upi',
  qrImageUrl: '',
  phone: '98765 43210',
  address: 'Your Shop Address, City',
  deliveryFee: 49,
  freeDeliveryAbove: 499,
  codEnabled: true,
  offers: [
    { title: 'Flat 20% OFF', text: 'on orders above ₹999' },
    { title: 'Free Delivery', text: 'on orders above ₹499' },
  ],
  announcements: [
    {
      id: 'demo-ann-1',
      title: 'New stock arrived!',
      text: 'Fresh collection of summer dresses is now live on the store.',
      date: '2026-08-13',
      active: true,
    },
  ],
  heroImageUrl: u('photo-1441986300917-64674bd600d8'),
}

export const DEMO_PRODUCTS = [
  {
    _id: 'demo-1',
    name: 'Classic Cotton T-Shirt (Men)',
    category: 'men',
    price: 399,
    mrp: 899,
    stock: 25,
    sizes: ['M', 'L', 'XL'],
    colors: ['White', 'Black', 'Navy'],
    image: u('photo-1521572163474-6864f9cf17ab'),
    description: '100% premium cotton, soft feel. Perfect everyday t-shirt for men.',
    featured: true,
  },
  {
    _id: 'demo-2',
    name: 'Graphic Print T-Shirt',
    category: 'boys',
    price: 349,
    mrp: 699,
    stock: 30,
    sizes: ['S', 'M', 'L'],
    colors: ['Grey', 'Black'],
    image: u('photo-1618354691373-d851c5c3a990'),
    description: 'Fun graphic print tee for boys, breathable fabric.',
    featured: true,
  },
  {
    _id: 'demo-3',
    name: 'Striped Casual Shirt',
    category: 'men',
    price: 599,
    mrp: 1299,
    stock: 15,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Blue', 'Green'],
    image: u('photo-1596755094514-f87e34085b2c'),
    description: 'Smart casual striped shirt, office and outing ready.',
    featured: false,
  },
  {
    _id: 'demo-4',
    name: 'Floral Summer Dress',
    category: 'women',
    price: 749,
    mrp: 1599,
    stock: 12,
    sizes: ['S', 'M', 'L'],
    colors: ['Floral Pink', 'Floral Blue'],
    image: u('photo-1595777457583-95e059d581b8'),
    description: 'Light summer dress with beautiful floral pattern.',
    featured: true,
  },
  {
    _id: 'demo-5',
    name: 'Kids Denim Jeans',
    category: 'children',
    price: 499,
    mrp: 999,
    stock: 20,
    sizes: ['2Y', '4Y', '6Y', '8Y'],
    colors: ['Blue'],
    image: u('photo-1523206489230-c012c64b2b48'),
    description: 'Comfortable denim jeans for kids, flexible waist.',
    featured: false,
  },
  {
    _id: 'demo-6',
    name: 'Party Frock for Girls',
    category: 'girls',
    price: 899,
    mrp: 1799,
    stock: 10,
    sizes: ['2Y', '4Y', '6Y'],
    colors: ['Pink', 'Red'],
    image: u('photo-1624109299037-94536fb186d5'),
    description: 'Beautiful party frock with soft lining for little girls.',
    featured: false,
  },
  {
    _id: 'demo-7',
    name: 'Oversized Hoodie',
    category: 'men',
    price: 799,
    mrp: 1899,
    stock: 18,
    sizes: ['M', 'L', 'XL'],
    colors: ['Black', 'Maroon'],
    image: u('photo-1556821840-3a63f95609a7'),
    description: 'Cozy oversized hoodie, fleece lined. Winter must-have.',
    featured: true,
  },
  {
    _id: 'demo-8',
    name: 'Saree Blouse Combo',
    category: 'women',
    price: 499,
    mrp: 999,
    stock: 22,
    sizes: ['Free Size'],
    colors: ['Multicolor'],
    image: u('photo-1610030469983-98e550d6193c'),
    description: 'Traditional blouse piece combo with print mix.',
    featured: false,
  },
  {
    _id: 'demo-9',
    name: 'Flannel Checked Shirt (Men)',
    category: 'men',
    price: 749,
    mrp: 1499,
    stock: 14,
    sizes: ['M', 'L', 'XL'],
    colors: ['Red Check', 'Blue Check'],
    image: u('photo-1596755094514-f87e34085b2c'),
    description: 'Soft flannel checked shirt, perfect for winter layering.',
    featured: false,
  },
  {
    _id: 'demo-10',
    name: 'Slim Fit Chinos',
    category: 'men',
    price: 899,
    mrp: 1799,
    stock: 16,
    sizes: ['30', '32', '34', '36'],
    colors: ['Beige', 'Black', 'Olive'],
    image: u('photo-1541099649105-f69ad21f3246'),
    description: 'Stretch slim-fit chinos — office and casual both.',
    featured: false,
  },
  {
    _id: 'demo-11',
    name: 'Anarkali Kurta',
    category: 'women',
    price: 999,
    mrp: 2199,
    stock: 9,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Maroon', 'Teal', 'Mustard'],
    image: u('photo-1584917865442-de89df76afd3'),
    description: 'Flowy Anarkali kurta with dupatta, festive ready.',
    featured: true,
  },
  {
    _id: 'demo-12',
    name: 'Cotton Leggings',
    category: 'women',
    price: 349,
    mrp: 699,
    stock: 28,
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Navy'],
    image: u('photo-1509631179647-0177331693ae'),
    description: 'Comfortable stretchable leggings for everyday wear.',
    featured: false,
  },
  {
    _id: 'demo-13',
    name: 'Poplin Shorts (Boys)',
    category: 'boys',
    price: 299,
    mrp: 599,
    stock: 24,
    sizes: ['S', 'M', 'L'],
    colors: ['Navy', 'Grey'],
    image: u('photo-1620799140408-edc6dcb6d633'),
    description: 'Breathable poplin shorts for active boys.',
    featured: false,
  },
  {
    _id: 'demo-14',
    name: 'Sports Jersey (Boys)',
    category: 'boys',
    price: 449,
    mrp: 999,
    stock: 18,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Green'],
    image: u('photo-1542291026-7eec264c27ff'),
    description: 'Quick-dry sports jersey, perfect for cricket and football.',
    featured: false,
  },
  {
    _id: 'demo-15',
    name: 'Skater Skirt (Girls)',
    category: 'girls',
    price: 399,
    mrp: 899,
    stock: 20,
    sizes: ['2Y', '4Y', '6Y', '8Y'],
    colors: ['Black', 'Pink', 'White'],
    image: u('photo-1595777457583-95e059d581b8'),
    description: 'Swingy skater skirt with soft elastic waistband.',
    featured: false,
  },
  {
    _id: 'demo-16',
    name: 'Cotton Romper (Baby & Kids)',
    category: 'children',
    price: 349,
    mrp: 749,
    stock: 26,
    sizes: ['0-6M', '6-12M', '1Y', '2Y'],
    colors: ['Yellow', 'White'],
    image: u('photo-1522771930-78848d9293e8'),
    description: 'Soft cotton romper for baby and toddler, easy wear.',
    featured: false,
  },
]